language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mkis98/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mkis98/react-test npm test

after_success:
  - docker build -t mkis98/multi-client ./client
  - docker build -t mkis98/multi-nginx ./nginx
  - docker build -t mkis98/multi-server ./server
  - docker build -t mkis98/multi-worker ./worker
  # login
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # push
  - docker push mkis98/multi-client
  - docker push mkis98/multi-nginx
  - docker push mkis98/multi-server
  - docker push mkis98/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "multi-docker"
    env: "Multidocker-env"
    bucket_name: "elasticbeanstalk-eu-central-1-102606406933"
    bucket_path: "multi-docker"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

